<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Authors>AndreCL</Authors>
    <Company>Luanca</Company>
    <Description>Localization library for use in Century and other projects.</Description>
    <PackageProjectUrl>
    </PackageProjectUrl>
    <RepositoryUrl>https://github.com/AndreCL/CenturyLocalization</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="Actions\Actions.Designer.cs">
      <DependentUpon>Actions.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="CountryNames\CountryNames.Designer.cs">
      <DependentUpon>CountryNames.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Diplomacy\Diplomacy.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Diplomacy.resx</DependentUpon>
    </Compile>
    <Compile Update="Events\Events.Designer.cs">
      <DependentUpon>Events.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="PopulationAttributes\PopulationAttributes.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PopulationAttributes.resx</DependentUpon>
    </Compile>
    <Compile Update="Texts.sk.Designer.cs">
      <DependentUpon>Texts.sk.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Texts.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Texts.resx</DependentUpon>
    </Compile>
    <Compile Update="WarNames\WarNames.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WarNames.resx</DependentUpon>
    </Compile>
    <Compile Update="BattleNames\BattleNames.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>BattleNames.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Actions\Actions.fr.resx" />
    <EmbeddedResource Update="Actions\Actions.da.resx" />
    <EmbeddedResource Update="Actions\Actions.es.resx" />
    <EmbeddedResource Update="Actions\Actions.resx">
      <LastGenOutput>Actions.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Actions\Actions.ru.resx" />
    <EmbeddedResource Update="CountryNames\CountryNames.fr.resx" />
    <EmbeddedResource Update="CountryNames\CountryNames.da.resx" />
    <EmbeddedResource Update="CountryNames\CountryNames.es.resx" />
    <EmbeddedResource Update="CountryNames\CountryNames.resx">
      <LastGenOutput>CountryNames.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="CountryNames\CountryNames.ru.resx" />
    <EmbeddedResource Update="Events\Events.fr.resx" />
    <EmbeddedResource Update="Events\Events.resx">
      <LastGenOutput>Events.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="PopulationAttributes\PopulationAttributes.fr.resx" />
    <EmbeddedResource Update="PopulationAttributes\PopulationAttributes.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>PopulationAttributes.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Texts.fr.resx" />
    <EmbeddedResource Update="Texts.sk.resx" />
    <EmbeddedResource Update="Texts.da.resx" />
    <EmbeddedResource Update="Texts.ru.resx" />
    <EmbeddedResource Update="Texts.es.resx" />
    <EmbeddedResource Update="Texts.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Texts.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="WarNames\WarNames.fr.resx" />
    <EmbeddedResource Update="WarNames\WarNames.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>WarNames.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="BattleNames\BattleNames.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>BattleNames.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="BattleNames\BattleNames.ar.resx" />
    <EmbeddedResource Update="BattleNames\BattleNames.da.resx" />
    <EmbeddedResource Update="BattleNames\BattleNames.de.resx" />
    <EmbeddedResource Update="BattleNames\BattleNames.es.resx" />
    <EmbeddedResource Update="BattleNames\BattleNames.fr.resx" />
    <EmbeddedResource Update="BattleNames\BattleNames.id.resx" />
    <EmbeddedResource Update="BattleNames\BattleNames.nl.resx" />
    <EmbeddedResource Update="BattleNames\BattleNames.pt-BR.resx" />
    <EmbeddedResource Update="BattleNames\BattleNames.pt-PT.resx" />
    <EmbeddedResource Update="BattleNames\BattleNames.ru.resx" />
    <EmbeddedResource Update="BattleNames\BattleNames.sk.resx" />
    <EmbeddedResource Update="BattleNames\BattleNames.tr.resx" />
    <EmbeddedResource Update="Diplomacy\Diplomacy.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Diplomacy.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Diplomacy\Diplomacy.ar.resx" />
    <EmbeddedResource Update="Diplomacy\Diplomacy.da.resx" />
    <EmbeddedResource Update="Diplomacy\Diplomacy.de.resx" />
    <EmbeddedResource Update="Diplomacy\Diplomacy.es.resx" />
    <EmbeddedResource Update="Diplomacy\Diplomacy.fr.resx" />
    <EmbeddedResource Update="Diplomacy\Diplomacy.id.resx" />
    <EmbeddedResource Update="Diplomacy\Diplomacy.nl.resx" />
    <EmbeddedResource Update="Diplomacy\Diplomacy.pt-BR.resx" />
    <EmbeddedResource Update="Diplomacy\Diplomacy.pt-PT.resx" />
    <EmbeddedResource Update="Diplomacy\Diplomacy.ru.resx" />
    <EmbeddedResource Update="Diplomacy\Diplomacy.sk.resx" />
    <EmbeddedResource Update="Diplomacy\Diplomacy.tr.resx" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="EndScreen\EndScreen.Designer.cs">
      <DependentUpon>EndScreen.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="EndScreen\EndScreen.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>EndScreen.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="EndScreen\EndScreen.ar.resx" />
    <EmbeddedResource Update="EndScreen\EndScreen.da.resx" />
    <EmbeddedResource Update="EndScreen\EndScreen.de.resx" />
    <EmbeddedResource Update="EndScreen\EndScreen.es.resx" />
    <EmbeddedResource Update="EndScreen\EndScreen.fr.resx" />
    <EmbeddedResource Update="EndScreen\EndScreen.id.resx" />
    <EmbeddedResource Update="EndScreen\EndScreen.nl.resx" />
    <EmbeddedResource Update="EndScreen\EndScreen.pt-BR.resx" />
    <EmbeddedResource Update="EndScreen\EndScreen.pt-PT.resx" />
    <EmbeddedResource Update="EndScreen\EndScreen.ru.resx" />
    <EmbeddedResource Update="EndScreen\EndScreen.sk.resx" />
    <EmbeddedResource Update="EndScreen\EndScreen.tr.resx" />
  </ItemGroup>
</Project>