//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenturyLocalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CenturyLocalization.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Groups.
        /// </summary>
        internal static string age_groups {
            get {
                return ResourceManager.GetString("age_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to air force school.
        /// </summary>
        internal static string air_school {
            get {
                return ResourceManager.GetString("air_school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to air force schools.
        /// </summary>
        internal static string air_schools {
            get {
                return ResourceManager.GetString("air_schools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air force.
        /// </summary>
        internal static string airforce {
            get {
                return ResourceManager.GetString("airforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {countryToDelete.Name} became so small and insignificant that {inherited.Name} has absorbed it.
        /// </summary>
        internal static string annexed_message {
            get {
                return ResourceManager.GetString("annexed_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annexation!.
        /// </summary>
        internal static string annexed_title {
            get {
                return ResourceManager.GetString("annexed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Century.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area:.
        /// </summary>
        internal static string area {
            get {
                return ResourceManager.GetString("area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Army.
        /// </summary>
        internal static string army {
            get {
                return ResourceManager.GetString("army", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to army school.
        /// </summary>
        internal static string army_school {
            get {
                return ResourceManager.GetString("army_school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to army schools.
        /// </summary>
        internal static string army_schools {
            get {
                return ResourceManager.GetString("army_schools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacker:.
        /// </summary>
        internal static string attacker {
            get {
                return ResourceManager.GetString("attacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacker victory.
        /// </summary>
        internal static string attacker_victory {
            get {
                return ResourceManager.GetString("attacker_victory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attackers:.
        /// </summary>
        internal static string attackers {
            get {
                return ResourceManager.GetString("attackers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battles.
        /// </summary>
        internal static string battles {
            get {
                return ResourceManager.GetString("battles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bombers:.
        /// </summary>
        internal static string bombers {
            get {
                return ResourceManager.GetString("bombers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        internal static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilian loses:.
        /// </summary>
        internal static string civilian_loses {
            get {
                return ResourceManager.GetString("civilian_loses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue game.
        /// </summary>
        internal static string Continuegame {
            get {
                return ResourceManager.GetString("Continuegame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        internal static string culture {
            get {
                return ResourceManager.GetString("culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily investment:.
        /// </summary>
        internal static string daily_investment {
            get {
                return ResourceManager.GetString("daily_investment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare war.
        /// </summary>
        internal static string declarewar {
            get {
                return ResourceManager.GetString("declarewar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {war.Name} has started between {war.Attackers[0].Name} and {war.Defenders[0].Name}..
        /// </summary>
        internal static string defaultwar_message {
            get {
                return ResourceManager.GetString("defaultwar_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After multiple aggressions from {highInfamyCountry.Name}, {attacker1.Name} and {attacker2.Name} have declared war upon the infamous {highInfamyCountry.Name}..
        /// </summary>
        internal static string defaultwar_message_infamy {
            get {
                return ResourceManager.GetString("defaultwar_message_infamy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War!.
        /// </summary>
        internal static string defaultwar_title {
            get {
                return ResourceManager.GetString("defaultwar_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender:.
        /// </summary>
        internal static string defender {
            get {
                return ResourceManager.GetString("defender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender victory.
        /// </summary>
        internal static string defender_victory {
            get {
                return ResourceManager.GetString("defender_victory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defenders:.
        /// </summary>
        internal static string defenders {
            get {
                return ResourceManager.GetString("defenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        internal static string discord {
            get {
                return ResourceManager.GetString("discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Discord server.
        /// </summary>
        internal static string discordjoin {
            get {
                return ResourceManager.GetString("discordjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dock.
        /// </summary>
        internal static string dock {
            get {
                return ResourceManager.GetString("dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to docks.
        /// </summary>
        internal static string docks {
            get {
                return ResourceManager.GetString("docks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        internal static string education {
            get {
                return ResourceManager.GetString("education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment.
        /// </summary>
        internal static string employment {
            get {
                return ResourceManager.GetString("employment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date:.
        /// </summary>
        internal static string enddate {
            get {
                return ResourceManager.GetString("enddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You led your nation through 100 tumultuous years.
        /// </summary>
        internal static string endgametitle {
            get {
                return ResourceManager.GetString("endgametitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment loses:.
        /// </summary>
        internal static string equipment_loses {
            get {
                return ResourceManager.GetString("equipment_loses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text not found.
        /// </summary>
        internal static string error_string_not_found {
            get {
                return ResourceManager.GetString("error_string_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have extra equipment.
        /// </summary>
        internal static string extra_equipment {
            get {
                return ResourceManager.GetString("extra_equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unequipped men.
        /// </summary>
        internal static string extra_men {
            get {
                return ResourceManager.GetString("extra_men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string facebook {
            get {
                return ResourceManager.GetString("facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Facebook group.
        /// </summary>
        internal static string facebookjoin {
            get {
                return ResourceManager.GetString("facebookjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to factories.
        /// </summary>
        internal static string factories {
            get {
                return ResourceManager.GetString("factories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to factory.
        /// </summary>
        internal static string factory {
            get {
                return ResourceManager.GetString("factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit your feedback.
        /// </summary>
        internal static string feedback {
            get {
                return ResourceManager.GetString("feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighters:.
        /// </summary>
        internal static string fighters {
            get {
                return ResourceManager.GetString("fighters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter wars.
        /// </summary>
        internal static string filter_wars {
            get {
                return ResourceManager.GetString("filter_wars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over.
        /// </summary>
        internal static string gameover {
            get {
                return ResourceManager.GetString("gameover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving version.
        /// </summary>
        internal static string getversion {
            get {
                return ResourceManager.GetString("getversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthcare coverage:.
        /// </summary>
        internal static string healthcare {
            get {
                return ResourceManager.GetString("healthcare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illiteracy:.
        /// </summary>
        internal static string illiteracy {
            get {
                return ResourceManager.GetString("illiteracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Millions of $.
        /// </summary>
        internal static string in_millions_hint {
            get {
                return ResourceManager.GetString("in_millions_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As one of the countries involved no longer exists, {warToRemove.Name} ended inconclusively.
        /// </summary>
        internal static string inconclusive_message {
            get {
                return ResourceManager.GetString("inconclusive_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {warToRemove.Name} ends inconclusively.
        /// </summary>
        internal static string inconclusive_title {
            get {
                return ResourceManager.GetString("inconclusive_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent since:.
        /// </summary>
        internal static string independentsince {
            get {
                return ResourceManager.GetString("independentsince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infamy:.
        /// </summary>
        internal static string infamy {
            get {
                return ResourceManager.GetString("infamy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure:.
        /// </summary>
        internal static string infrastructure {
            get {
                return ResourceManager.GetString("infrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure loss:.
        /// </summary>
        internal static string infrastructure_decrease {
            get {
                return ResourceManager.GetString("infrastructure_decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a country.
        /// </summary>
        internal static string Instructions1 {
            get {
                return ResourceManager.GetString("Instructions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invest.
        /// </summary>
        internal static string invest {
            get {
                return ResourceManager.GetString("invest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large ships:.
        /// </summary>
        internal static string largeships {
            get {
                return ResourceManager.GetString("largeships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largest culture:.
        /// </summary>
        internal static string largestculture {
            get {
                return ResourceManager.GetString("largestculture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largest religion:.
        /// </summary>
        internal static string largestreligion {
            get {
                return ResourceManager.GetString("largestreligion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading saves....
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium ships:.
        /// </summary>
        internal static string mediumships {
            get {
                return ResourceManager.GetString("mediumships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men to Equipment ratio: .
        /// </summary>
        internal static string men_to_equipment {
            get {
                return ResourceManager.GetString("men_to_equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this saved game?.
        /// </summary>
        internal static string message_delete_save {
            get {
                return ResourceManager.GetString("message_delete_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military loses:.
        /// </summary>
        internal static string military_loses {
            get {
                return ResourceManager.GetString("military_loses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money:.
        /// </summary>
        internal static string money {
            get {
                return ResourceManager.GetString("money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navy.
        /// </summary>
        internal static string navy {
            get {
                return ResourceManager.GetString("navy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to navy school.
        /// </summary>
        internal static string navy_school {
            get {
                return ResourceManager.GetString("navy_school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to navy schools.
        /// </summary>
        internal static string navy_schools {
            get {
                return ResourceManager.GetString("navy_schools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear readers,
        ///A new century is upon us. We wish you a happy new year. May this new time be peaceful..
        /// </summary>
        internal static string new_century_message {
            get {
                return ResourceManager.GetString("new_century_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy New Century!.
        /// </summary>
        internal static string new_century_title {
            get {
                return ResourceManager.GetString("new_century_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear readers,
        ///A new year is upon us. We wish you a happy new year. May this new time be peaceful..
        /// </summary>
        internal static string new_year_message {
            get {
                return ResourceManager.GetString("new_year_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy New Year!.
        /// </summary>
        internal static string new_year_title {
            get {
                return ResourceManager.GetString("new_year_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        internal static string Newgame {
            get {
                return ResourceManager.GetString("Newgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected country no longer exists.
        /// </summary>
        internal static string no_longer_exists {
            get {
                return ResourceManager.GetString("no_longer_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One time investment:.
        /// </summary>
        internal static string one_time_investment {
            get {
                return ResourceManager.GetString("one_time_investment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilots:.
        /// </summary>
        internal static string pilots {
            get {
                return ResourceManager.GetString("pilots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population:.
        /// </summary>
        internal static string population {
            get {
                return ResourceManager.GetString("population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poverty:.
        /// </summary>
        internal static string poverty {
            get {
                return ResourceManager.GetString("poverty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string rank {
            get {
                return ResourceManager.GetString("rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        internal static string religion {
            get {
                return ResourceManager.GetString("religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rifles:.
        /// </summary>
        internal static string rifles {
            get {
                return ResourceManager.GetString("rifles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sailors:.
        /// </summary>
        internal static string sailors {
            get {
                return ResourceManager.GetString("sailors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd:.
        /// </summary>
        internal static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send e-mail.
        /// </summary>
        internal static string sendemail {
            get {
                return ResourceManager.GetString("sendemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small ships:.
        /// </summary>
        internal static string smallships {
            get {
                return ResourceManager.GetString("smallships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social class.
        /// </summary>
        internal static string social_class {
            get {
                return ResourceManager.GetString("social_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldiers:.
        /// </summary>
        internal static string soldiers {
            get {
                return ResourceManager.GetString("soldiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date:.
        /// </summary>
        internal static string startdate {
            get {
                return ResourceManager.GetString("startdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanks:.
        /// </summary>
        internal static string tanks {
            get {
                return ResourceManager.GetString("tanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd:.
        /// </summary>
        internal static string third {
            get {
                return ResourceManager.GetString("third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tie.
        /// </summary>
        internal static string tie {
            get {
                return ResourceManager.GetString("tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string unittest_both {
            get {
                return ResourceManager.GetString("unittest_both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string unittest_onlyen {
            get {
                return ResourceManager.GetString("unittest_onlyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edward VII becomes King of England and India after Queen Victoria&apos;s death.
        /// </summary>
        internal static string victoria_message {
            get {
                return ResourceManager.GetString("victoria_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen Victoria dead.
        /// </summary>
        internal static string victoria_title {
            get {
                return ResourceManager.GetString("victoria_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War.
        /// </summary>
        internal static string war {
            get {
                return ResourceManager.GetString("war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War level:.
        /// </summary>
        internal static string war_level {
            get {
                return ResourceManager.GetString("war_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner:.
        /// </summary>
        internal static string winner {
            get {
                return ResourceManager.GetString("winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Tension.
        /// </summary>
        internal static string world_tension {
            get {
                return ResourceManager.GetString("world_tension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After months of high tensions, the great powers have gone to war. {war.Name} has started..
        /// </summary>
        internal static string world_war_message {
            get {
                return ResourceManager.GetString("world_war_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The World is at War!.
        /// </summary>
        internal static string world_war_title {
            get {
                return ResourceManager.GetString("world_war_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
