//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenturyLocalization.WarNames {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WarNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WarNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CenturyLocalization.WarNames.WarNames", typeof(WarNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Acre War.
        /// </summary>
        internal static string acre_war {
            get {
                return ResourceManager.GetString("acre_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Anglo-Aro War.
        /// </summary>
        internal static string anglo_aro_war {
            get {
                return ResourceManager.GetString("anglo_aro_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Boxer Rebellion.
        /// </summary>
        internal static string boxer_rebellion {
            get {
                return ResourceManager.GetString("boxer_rebellion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War of the Golden Stool.
        /// </summary>
        internal static string golden_stool_war {
            get {
                return ResourceManager.GetString("golden_stool_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holy Man&apos;s Rebellion.
        /// </summary>
        internal static string holy_mans_rebellion {
            get {
                return ResourceManager.GetString("holy_mans_rebellion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean Invasion of Manchuria.
        /// </summary>
        internal static string korean_invasion_of_manchuria {
            get {
                return ResourceManager.GetString("korean_invasion_of_manchuria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Second Boer War.
        /// </summary>
        internal static string second_boer_war {
            get {
                return ResourceManager.GetString("second_boer_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuelan Crisis.
        /// </summary>
        internal static string venezuelan_crisis {
            get {
                return ResourceManager.GetString("venezuelan_crisis", resourceCulture);
            }
        }
    }
}
