//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenturyLocalization.WarNames {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WarNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WarNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CenturyLocalization.WarNames.WarNames", typeof(WarNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Acre War.
        /// </summary>
        internal static string acre_war {
            get {
                return ResourceManager.GetString("acre_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Anglo-Aro War.
        /// </summary>
        internal static string anglo_aro_war {
            get {
                return ResourceManager.GetString("anglo_aro_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Boxer Rebellion.
        /// </summary>
        internal static string boxer_rebellion {
            get {
                return ResourceManager.GetString("boxer_rebellion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British annexation of the Sokoto.
        /// </summary>
        internal static string british_annexation_sokoto {
            get {
                return ResourceManager.GetString("british_annexation_sokoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British expedition to Tibet.
        /// </summary>
        internal static string british_expedition_tibet {
            get {
                return ResourceManager.GetString("british_expedition_tibet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch annexation of Aceh.
        /// </summary>
        internal static string dutch_annexation_aceh {
            get {
                return ResourceManager.GetString("dutch_annexation_aceh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch intervention in Bali.
        /// </summary>
        internal static string dutch_intervention_in_bali {
            get {
                return ResourceManager.GetString("dutch_intervention_in_bali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch–Venezuelan crisis.
        /// </summary>
        internal static string dutch_venezuelan_crisis {
            get {
                return ResourceManager.GetString("dutch_venezuelan_crisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Empty War.
        /// </summary>
        internal static string empty_war {
            get {
                return ResourceManager.GetString("empty_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Balkan War.
        /// </summary>
        internal static string first_balkan_war {
            get {
                return ResourceManager.GetString("first_balkan_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French annexation of Agadez.
        /// </summary>
        internal static string french_annexation_agadez {
            get {
                return ResourceManager.GetString("french_annexation_agadez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French conquest of Morocco.
        /// </summary>
        internal static string french_conquest_of_morocco {
            get {
                return ResourceManager.GetString("french_conquest_of_morocco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War of the Golden Stool.
        /// </summary>
        internal static string golden_stool_war {
            get {
                return ResourceManager.GetString("golden_stool_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holy Man&apos;s Rebellion.
        /// </summary>
        internal static string holy_mans_rebellion {
            get {
                return ResourceManager.GetString("holy_mans_rebellion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} War of Independence from {1}.
        /// </summary>
        internal static string independence_war {
            get {
                return ResourceManager.GetString("independence_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italo-Turkish War.
        /// </summary>
        internal static string italo_turkish_war {
            get {
                return ResourceManager.GetString("italo_turkish_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean Invasion of Manchuria.
        /// </summary>
        internal static string korean_invasion_of_manchuria {
            get {
                return ResourceManager.GetString("korean_invasion_of_manchuria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Portuguese conquest of Angoche.
        /// </summary>
        internal static string portuguese_conquest_angoche {
            get {
                return ResourceManager.GetString("portuguese_conquest_angoche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russo-Japanese War.
        /// </summary>
        internal static string ruso_japanese_war {
            get {
                return ResourceManager.GetString("ruso_japanese_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian invasion of Manchuria.
        /// </summary>
        internal static string russian_invasion_manchuria {
            get {
                return ResourceManager.GetString("russian_invasion_manchuria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Balkan War.
        /// </summary>
        internal static string second_balkan_war {
            get {
                return ResourceManager.GetString("second_balkan_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Second Boer War.
        /// </summary>
        internal static string second_boer_war {
            get {
                return ResourceManager.GetString("second_boer_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Great War.
        /// </summary>
        internal static string the_great_war {
            get {
                return ResourceManager.GetString("the_great_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuelan Crisis.
        /// </summary>
        internal static string venezuelan_crisis {
            get {
                return ResourceManager.GetString("venezuelan_crisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War of 1907.
        /// </summary>
        internal static string war_of_1907 {
            get {
                return ResourceManager.GetString("war_of_1907", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World War {0}.
        /// </summary>
        internal static string world_war {
            get {
                return ResourceManager.GetString("world_war", resourceCulture);
            }
        }
    }
}
