//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenturyLocalization.EndScreen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EndScreen {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EndScreen() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CenturyLocalization.EndScreen.EndScreen", typeof(EndScreen).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best trains and roads.
        /// </summary>
        internal static string best_trains_roads {
            get {
                return ResourceManager.GetString("best_trains_roads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You led your nation through {0} tumultuous years.
        /// </summary>
        internal static string endgametitle {
            get {
                return ResourceManager.GetString("endgametitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land of Endless Frontiers.
        /// </summary>
        internal static string endless_frontiers {
            get {
                return ResourceManager.GetString("endless_frontiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Nation was defeated after {0} years.
        /// </summary>
        internal static string gameover {
            get {
                return ResourceManager.GetString("gameover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hordes of Genghis Khan.
        /// </summary>
        internal static string hordes_of_genghis_khan {
            get {
                return ResourceManager.GetString("hordes_of_genghis_khan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerous as the stars.
        /// </summary>
        internal static string numerous_as_stars {
            get {
                return ResourceManager.GetString("numerous_as_stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragon of Peace.
        /// </summary>
        internal static string paragon_of_peace {
            get {
                return ResourceManager.GetString("paragon_of_peace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd.
        /// </summary>
        internal static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sovereign of the Seas.
        /// </summary>
        internal static string sovereign_sea {
            get {
                return ResourceManager.GetString("sovereign_sea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd.
        /// </summary>
        internal static string third {
            get {
                return ResourceManager.GetString("third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrior Nation.
        /// </summary>
        internal static string warrior_nation {
            get {
                return ResourceManager.GetString("warrior_nation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winged Armada.
        /// </summary>
        internal static string winged_armada {
            get {
                return ResourceManager.GetString("winged_armada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        internal static string winner {
            get {
                return ResourceManager.GetString("winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You conquered the world in {0} years.
        /// </summary>
        internal static string worldconquesttitle {
            get {
                return ResourceManager.GetString("worldconquesttitle", resourceCulture);
            }
        }
    }
}
