//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenturyLocalization.AllianceNames {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AllianceNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AllianceNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CenturyLocalization.AllianceNames.AllianceNames", typeof(AllianceNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allied Powers.
        /// </summary>
        internal static string allied_powers {
            get {
                return ResourceManager.GetString("allied_powers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anglo-Japanese Alliance.
        /// </summary>
        internal static string anglo_japanese_alliance {
            get {
                return ResourceManager.GetString("anglo_japanese_alliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anglo-Portuguese Alliance.
        /// </summary>
        internal static string anglo_portuguese_alliance {
            get {
                return ResourceManager.GetString("anglo_portuguese_alliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Powers.
        /// </summary>
        internal static string central_powers {
            get {
                return ResourceManager.GetString("central_powers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual Alliance.
        /// </summary>
        internal static string dual_alliance {
            get {
                return ResourceManager.GetString("dual_alliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entente Cordiale.
        /// </summary>
        internal static string entente_cordiale {
            get {
                return ResourceManager.GetString("entente_cordiale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franco-Russian Alliance.
        /// </summary>
        internal static string franco_russian_alliance {
            get {
                return ResourceManager.GetString("franco_russian_alliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triple Alliance.
        /// </summary>
        internal static string triple_alliance {
            get {
                return ResourceManager.GetString("triple_alliance", resourceCulture);
            }
        }
    }
}
