//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenturyLocalization.BattleNames {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BattleNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BattleNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CenturyLocalization.BattleNames.BattleNames", typeof(BattleNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle of Bekwai.
        /// </summary>
        internal static string battle_of_bekwai {
            get {
                return ResourceManager.GetString("battle_of_bekwai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle of Kokofu.
        /// </summary>
        internal static string battle_of_kokofu {
            get {
                return ResourceManager.GetString("battle_of_kokofu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle of Kumasi.
        /// </summary>
        internal static string battle_of_kumasi {
            get {
                return ResourceManager.GetString("battle_of_kumasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle of Obassa.
        /// </summary>
        internal static string battle_of_obassa {
            get {
                return ResourceManager.GetString("battle_of_obassa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle of Xapuri.
        /// </summary>
        internal static string battle_of_xapuri {
            get {
                return ResourceManager.GetString("battle_of_xapuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle of Volta da Empresa.
        /// </summary>
        internal static string battle_volta_empresa {
            get {
                return ResourceManager.GetString("battle_volta_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign of Placido de Castro.
        /// </summary>
        internal static string campaign_placido_castro {
            get {
                return ResourceManager.GetString("campaign_placido_castro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Acrean Revolt.
        /// </summary>
        internal static string first_acre_revolt {
            get {
                return ResourceManager.GetString("first_acre_revolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Acrean Revolt.
        /// </summary>
        internal static string second_acre_revolt {
            get {
                return ResourceManager.GetString("second_acre_revolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Battle of Kumasi.
        /// </summary>
        internal static string second_battle_of_kumasi {
            get {
                return ResourceManager.GetString("second_battle_of_kumasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siege of Puerto Alonso.
        /// </summary>
        internal static string siege_puerto_alfonso {
            get {
                return ResourceManager.GetString("siege_puerto_alfonso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Acrean Revolt.
        /// </summary>
        internal static string third_acre_revolt {
            get {
                return ResourceManager.GetString("third_acre_revolt", resourceCulture);
            }
        }
    }
}
