//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenturyLocalization.Actions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Actions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Actions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CenturyLocalization.Actions.Actions", typeof(Actions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Christian Population.
        /// </summary>
        internal static string add_christian_population {
            get {
                return ResourceManager.GetString("add_christian_population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add soldiers.
        /// </summary>
        internal static string add_soldiers {
            get {
                return ResourceManager.GetString("add_soldiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Flag.
        /// </summary>
        internal static string change_flag {
            get {
                return ResourceManager.GetString("change_flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country not found.
        /// </summary>
        internal static string country_not_found {
            get {
                return ResourceManager.GetString("country_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demobilize soldiers.
        /// </summary>
        internal static string demobilize_soldiers {
            get {
                return ResourceManager.GetString("demobilize_soldiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join World War Coalition Attackers.
        /// </summary>
        internal static string join_world_war_coalition_attackers {
            get {
                return ResourceManager.GetString("join_world_war_coalition_attackers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join World War Coalition Defenders.
        /// </summary>
        internal static string join_world_war_coalition_defenders {
            get {
                return ResourceManager.GetString("join_world_war_coalition_defenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobilize soldiers.
        /// </summary>
        internal static string mobilize_soldiers {
            get {
                return ResourceManager.GetString("mobilize_soldiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Christianity.
        /// </summary>
        internal static string move_from_christian {
            get {
                return ResourceManager.GetString("move_from_christian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Christianity.
        /// </summary>
        internal static string move_to_christian {
            get {
                return ResourceManager.GetString("move_to_christian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play as {0}.
        /// </summary>
        internal static string play_as_country {
            get {
                return ResourceManager.GetString("play_as_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Christian Population.
        /// </summary>
        internal static string remove_christian_population {
            get {
                return ResourceManager.GetString("remove_christian_population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove soldiers.
        /// </summary>
        internal static string remove_soldiers {
            get {
                return ResourceManager.GetString("remove_soldiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start World War.
        /// </summary>
        internal static string start_world_war {
            get {
                return ResourceManager.GetString("start_world_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch country name to {0}.
        /// </summary>
        internal static string switch_name_country {
            get {
                return ResourceManager.GetString("switch_name_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger event {0}.
        /// </summary>
        internal static string trigger_event {
            get {
                return ResourceManager.GetString("trigger_event", resourceCulture);
            }
        }
    }
}
