//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenturyLocalization.Diplomacy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Diplomacy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Diplomacy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CenturyLocalization.Diplomacy.Diplomacy", typeof(Diplomacy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allies in war.
        /// </summary>
        internal static string diplomacy_allies_in_war {
            get {
                return ResourceManager.GetString("diplomacy_allies_in_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At War.
        /// </summary>
        internal static string diplomacy_effect_at_war {
            get {
                return ResourceManager.GetString("diplomacy_effect_at_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Drift.
        /// </summary>
        internal static string diplomacy_effect_daily_drift {
            get {
                return ResourceManager.GetString("diplomacy_effect_daily_drift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different Culture.
        /// </summary>
        internal static string diplomacy_effect_different_culture {
            get {
                return ResourceManager.GetString("diplomacy_effect_different_culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different Culture Group.
        /// </summary>
        internal static string diplomacy_effect_different_culture_group {
            get {
                return ResourceManager.GetString("diplomacy_effect_different_culture_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different Religion.
        /// </summary>
        internal static string diplomacy_effect_different_religion {
            get {
                return ResourceManager.GetString("diplomacy_effect_different_religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infamy.
        /// </summary>
        internal static string diplomacy_effect_infamy {
            get {
                return ResourceManager.GetString("diplomacy_effect_infamy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Culture.
        /// </summary>
        internal static string diplomacy_effect_same_culture {
            get {
                return ResourceManager.GetString("diplomacy_effect_same_culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Culture Group.
        /// </summary>
        internal static string diplomacy_effect_same_culture_group {
            get {
                return ResourceManager.GetString("diplomacy_effect_same_culture_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Religion.
        /// </summary>
        internal static string diplomacy_effect_same_religion {
            get {
                return ResourceManager.GetString("diplomacy_effect_same_religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Change.
        /// </summary>
        internal static string diplomacy_relationship_change {
            get {
                return ResourceManager.GetString("diplomacy_relationship_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplomacy.
        /// </summary>
        internal static string diplomacy_title {
            get {
                return ResourceManager.GetString("diplomacy_title", resourceCulture);
            }
        }
    }
}
