//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenturyLocalization.PopulationAttributes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PopulationAttributes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PopulationAttributes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CenturyLocalization.PopulationAttributes.PopulationAttributes", typeof(PopulationAttributes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Groups.
        /// </summary>
        internal static string age_groups {
            get {
                return ResourceManager.GetString("age_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buddhist.
        /// </summary>
        internal static string buddhist {
            get {
                return ResourceManager.GetString("buddhist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christian.
        /// </summary>
        internal static string christian {
            get {
                return ResourceManager.GetString("christian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        internal static string culture {
            get {
                return ResourceManager.GetString("culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture groups.
        /// </summary>
        internal static string culture_groups {
            get {
                return ResourceManager.GetString("culture_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultures.
        /// </summary>
        internal static string cultures {
            get {
                return ResourceManager.GetString("cultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctoral.
        /// </summary>
        internal static string doctoral {
            get {
                return ResourceManager.GetString("doctoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        internal static string education {
            get {
                return ResourceManager.GetString("education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Attainment.
        /// </summary>
        internal static string education_attainment {
            get {
                return ResourceManager.GetString("education_attainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment.
        /// </summary>
        internal static string employment {
            get {
                return ResourceManager.GetString("employment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduate.
        /// </summary>
        internal static string graduate {
            get {
                return ResourceManager.GetString("graduate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindu.
        /// </summary>
        internal static string hindu {
            get {
                return ResourceManager.GetString("hindu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jain.
        /// </summary>
        internal static string jain {
            get {
                return ResourceManager.GetString("jain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewish.
        /// </summary>
        internal static string jewish {
            get {
                return ResourceManager.GetString("jewish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        internal static string middle {
            get {
                return ResourceManager.GetString("middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muslim.
        /// </summary>
        internal static string muslim {
            get {
                return ResourceManager.GetString("muslim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor.
        /// </summary>
        internal static string poor {
            get {
                return ResourceManager.GetString("poor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postgraduate.
        /// </summary>
        internal static string postgraduate {
            get {
                return ResourceManager.GetString("postgraduate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        internal static string primary {
            get {
                return ResourceManager.GetString("primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        internal static string religion {
            get {
                return ResourceManager.GetString("religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich.
        /// </summary>
        internal static string rich {
            get {
                return ResourceManager.GetString("rich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        internal static string secondary {
            get {
                return ResourceManager.GetString("secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secular.
        /// </summary>
        internal static string secular {
            get {
                return ResourceManager.GetString("secular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shinto.
        /// </summary>
        internal static string shinto {
            get {
                return ResourceManager.GetString("shinto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikh.
        /// </summary>
        internal static string sikh {
            get {
                return ResourceManager.GetString("sikh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social class.
        /// </summary>
        internal static string social_class {
            get {
                return ResourceManager.GetString("social_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional.
        /// </summary>
        internal static string traditional {
            get {
                return ResourceManager.GetString("traditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoroastrian.
        /// </summary>
        internal static string zoroastrian {
            get {
                return ResourceManager.GetString("zoroastrian", resourceCulture);
            }
        }
    }
}
