//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenturyLocalization.PopulationAttributes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PopulationAttributes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PopulationAttributes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CenturyLocalization.PopulationAttributes.PopulationAttributes", typeof(PopulationAttributes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buddhist.
        /// </summary>
        internal static string buddhist {
            get {
                return ResourceManager.GetString("buddhist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christian.
        /// </summary>
        internal static string christian {
            get {
                return ResourceManager.GetString("christian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindu.
        /// </summary>
        internal static string hindu {
            get {
                return ResourceManager.GetString("hindu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jain.
        /// </summary>
        internal static string jain {
            get {
                return ResourceManager.GetString("jain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewish.
        /// </summary>
        internal static string jewish {
            get {
                return ResourceManager.GetString("jewish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        internal static string middle {
            get {
                return ResourceManager.GetString("middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muslim.
        /// </summary>
        internal static string muslim {
            get {
                return ResourceManager.GetString("muslim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor.
        /// </summary>
        internal static string poor {
            get {
                return ResourceManager.GetString("poor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich.
        /// </summary>
        internal static string rich {
            get {
                return ResourceManager.GetString("rich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secular.
        /// </summary>
        internal static string secular {
            get {
                return ResourceManager.GetString("secular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shinto.
        /// </summary>
        internal static string shinto {
            get {
                return ResourceManager.GetString("shinto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikh.
        /// </summary>
        internal static string sikh {
            get {
                return ResourceManager.GetString("sikh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional.
        /// </summary>
        internal static string traditional {
            get {
                return ResourceManager.GetString("traditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoroastrian.
        /// </summary>
        internal static string zoroastrian {
            get {
                return ResourceManager.GetString("zoroastrian", resourceCulture);
            }
        }
    }
}
