//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenturyLocalization.Events {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Events {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Events() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CenturyLocalization.Events.Events", typeof(Events).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We want to annex {0}.
        /// </summary>
        internal static string annex_country {
            get {
                return ResourceManager.GetString("annex_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has annexed {1} with a population of {2} and area of {3}..
        /// </summary>
        internal static string annexed_message {
            get {
                return ResourceManager.GetString("annexed_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annexation!.
        /// </summary>
        internal static string annexed_title {
            get {
                return ResourceManager.GetString("annexed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We want {0} land from {1}.
        /// </summary>
        internal static string conquer_land {
            get {
                return ResourceManager.GetString("conquer_land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We want {0} in economic compensation from {1}.
        /// </summary>
        internal static string economic_compensation {
            get {
                return ResourceManager.GetString("economic_compensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famine!.
        /// </summary>
        internal static string famine_title {
            get {
                return ResourceManager.GetString("famine_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overpopulation has lead to famine and substantial economic losses around the world. The death of {0} people worldwide to starvation has taken the world population from {1} to {2}. Countries worldwide have spent {3} in an attempt to save their citizens from starvation. Tensions and conflicts are on the rise due to lack of food supplies..
        /// </summary>
        internal static string global_famine_message {
            get {
                return ResourceManager.GetString("global_famine_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We just want peace.
        /// </summary>
        internal static string just_peace {
            get {
                return ResourceManager.GetString("just_peace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will do this later.
        /// </summary>
        internal static string later {
            get {
                return ResourceManager.GetString("later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overpopulation in {0} leads to Famine. The death of {1} people to starvation in {0} has shocked the world. Their population has gone from from {2} to {3}. {0} has spent {4} in an attempt to save its citizens from starvation..
        /// </summary>
        internal static string local_famine_message {
            get {
                return ResourceManager.GetString("local_famine_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select war goal.
        /// </summary>
        internal static string select_war_goal {
            get {
                return ResourceManager.GetString("select_war_goal", resourceCulture);
            }
        }
    }
}
