//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenturyLocalization.CountryNames {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CountryNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CountryNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CenturyLocalization.CountryNames.CountryNames", typeof(CountryNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceh.
        /// </summary>
        internal static string aceh {
            get {
                return ResourceManager.GetString("aceh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acre.
        /// </summary>
        internal static string acre {
            get {
                return ResourceManager.GetString("acre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan.
        /// </summary>
        internal static string afghanistan {
            get {
                return ResourceManager.GetString("afghanistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agadez.
        /// </summary>
        internal static string agadez {
            get {
                return ResourceManager.GetString("agadez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andorra.
        /// </summary>
        internal static string andorra {
            get {
                return ResourceManager.GetString("andorra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angoche.
        /// </summary>
        internal static string angoche {
            get {
                return ResourceManager.GetString("angoche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ankole.
        /// </summary>
        internal static string ankole {
            get {
                return ResourceManager.GetString("ankole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina.
        /// </summary>
        internal static string argentina {
            get {
                return ResourceManager.GetString("argentina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aro.
        /// </summary>
        internal static string aro {
            get {
                return ResourceManager.GetString("aro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ashanti.
        /// </summary>
        internal static string ashanti {
            get {
                return ResourceManager.GetString("ashanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aussa.
        /// </summary>
        internal static string aussa {
            get {
                return ResourceManager.GetString("aussa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        internal static string australia {
            get {
                return ResourceManager.GetString("australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austria-Hungary.
        /// </summary>
        internal static string austria_hungary {
            get {
                return ResourceManager.GetString("austria-hungary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bali.
        /// </summary>
        internal static string bali {
            get {
                return ResourceManager.GetString("bali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium.
        /// </summary>
        internal static string belgium {
            get {
                return ResourceManager.GetString("belgium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bhutan.
        /// </summary>
        internal static string bhutan {
            get {
                return ResourceManager.GetString("bhutan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolivia.
        /// </summary>
        internal static string bolivia {
            get {
                return ResourceManager.GetString("bolivia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil.
        /// </summary>
        internal static string brazil {
            get {
                return ResourceManager.GetString("brazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgaria.
        /// </summary>
        internal static string bulgaria {
            get {
                return ResourceManager.GetString("bulgaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        internal static string canada {
            get {
                return ResourceManager.GetString("canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champasak.
        /// </summary>
        internal static string champasak {
            get {
                return ResourceManager.GetString("champasak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chile.
        /// </summary>
        internal static string chile {
            get {
                return ResourceManager.GetString("chile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China.
        /// </summary>
        internal static string china {
            get {
                return ResourceManager.GetString("china", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chokwe.
        /// </summary>
        internal static string chokwe {
            get {
                return ResourceManager.GetString("chokwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombia.
        /// </summary>
        internal static string colombia {
            get {
                return ResourceManager.GetString("colombia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congo.
        /// </summary>
        internal static string congo {
            get {
                return ResourceManager.GetString("congo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costa Rica.
        /// </summary>
        internal static string costa_rica {
            get {
                return ResourceManager.GetString("costa_rica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuba.
        /// </summary>
        internal static string cuba {
            get {
                return ResourceManager.GetString("cuba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark.
        /// </summary>
        internal static string denmark {
            get {
                return ResourceManager.GetString("denmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominican Republic.
        /// </summary>
        internal static string dominican_republic {
            get {
                return ResourceManager.GetString("dominican_republic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecuador.
        /// </summary>
        internal static string ecuador {
            get {
                return ResourceManager.GetString("ecuador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Salvador.
        /// </summary>
        internal static string el_salvador {
            get {
                return ResourceManager.GetString("el_salvador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethiopia.
        /// </summary>
        internal static string ethiopia {
            get {
                return ResourceManager.GetString("ethiopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finland.
        /// </summary>
        internal static string finland {
            get {
                return ResourceManager.GetString("finland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        internal static string france {
            get {
                return ResourceManager.GetString("france", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        internal static string germany {
            get {
                return ResourceManager.GetString("germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greece.
        /// </summary>
        internal static string greece {
            get {
                return ResourceManager.GetString("greece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guatemala.
        /// </summary>
        internal static string guatemala {
            get {
                return ResourceManager.GetString("guatemala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haiti.
        /// </summary>
        internal static string haiti {
            get {
                return ResourceManager.GetString("haiti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honduras.
        /// </summary>
        internal static string honduras {
            get {
                return ResourceManager.GetString("honduras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        internal static string italy {
            get {
                return ResourceManager.GetString("italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        internal static string japan {
            get {
                return ResourceManager.GetString("japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korea.
        /// </summary>
        internal static string korea {
            get {
                return ResourceManager.GetString("korea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberia.
        /// </summary>
        internal static string liberia {
            get {
                return ResourceManager.GetString("liberia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liechtenstein.
        /// </summary>
        internal static string liechtenstein {
            get {
                return ResourceManager.GetString("liechtenstein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg.
        /// </summary>
        internal static string luxembourg {
            get {
                return ResourceManager.GetString("luxembourg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico.
        /// </summary>
        internal static string mexico {
            get {
                return ResourceManager.GetString("mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monaco.
        /// </summary>
        internal static string monaco {
            get {
                return ResourceManager.GetString("monaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montenegro.
        /// </summary>
        internal static string montenegro {
            get {
                return ResourceManager.GetString("montenegro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morocco.
        /// </summary>
        internal static string morocco {
            get {
                return ResourceManager.GetString("morocco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muscat and Oman.
        /// </summary>
        internal static string muscat_and_oman {
            get {
                return ResourceManager.GetString("muscat_and_oman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepal.
        /// </summary>
        internal static string nepal {
            get {
                return ResourceManager.GetString("nepal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands.
        /// </summary>
        internal static string netherlands {
            get {
                return ResourceManager.GetString("netherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicaragua.
        /// </summary>
        internal static string nicaragua {
            get {
                return ResourceManager.GetString("nicaragua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway.
        /// </summary>
        internal static string norway {
            get {
                return ResourceManager.GetString("norway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange Free State.
        /// </summary>
        internal static string orange_free_state {
            get {
                return ResourceManager.GetString("orange_free_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ottoman Empire.
        /// </summary>
        internal static string ottomans {
            get {
                return ResourceManager.GetString("ottomans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panama.
        /// </summary>
        internal static string panama {
            get {
                return ResourceManager.GetString("panama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraguay.
        /// </summary>
        internal static string paraguay {
            get {
                return ResourceManager.GetString("paraguay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persia.
        /// </summary>
        internal static string persia {
            get {
                return ResourceManager.GetString("persia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peru.
        /// </summary>
        internal static string peru {
            get {
                return ResourceManager.GetString("peru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal.
        /// </summary>
        internal static string portugal {
            get {
                return ResourceManager.GetString("portugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romania.
        /// </summary>
        internal static string romania {
            get {
                return ResourceManager.GetString("romania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        internal static string russia {
            get {
                return ResourceManager.GetString("russia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to San Marino.
        /// </summary>
        internal static string san_marino {
            get {
                return ResourceManager.GetString("san_marino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbia.
        /// </summary>
        internal static string serbia {
            get {
                return ResourceManager.GetString("serbia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siam.
        /// </summary>
        internal static string siam {
            get {
                return ResourceManager.GetString("siam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sokoto Caliphate.
        /// </summary>
        internal static string sokoto {
            get {
                return ResourceManager.GetString("sokoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        internal static string spain {
            get {
                return ResourceManager.GetString("spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden.
        /// </summary>
        internal static string sweden {
            get {
                return ResourceManager.GetString("sweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden and Norway.
        /// </summary>
        internal static string sweden_norway {
            get {
                return ResourceManager.GetString("sweden-norway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        internal static string switzerland {
            get {
                return ResourceManager.GetString("switzerland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transvaal.
        /// </summary>
        internal static string transvaal {
            get {
                return ResourceManager.GetString("transvaal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom.
        /// </summary>
        internal static string united_kingdom {
            get {
                return ResourceManager.GetString("united_kingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States.
        /// </summary>
        internal static string united_states {
            get {
                return ResourceManager.GetString("united_states", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruguay.
        /// </summary>
        internal static string uruguay {
            get {
                return ResourceManager.GetString("uruguay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuela.
        /// </summary>
        internal static string venezuela {
            get {
                return ResourceManager.GetString("venezuela", resourceCulture);
            }
        }
    }
}
